CREATE DATABASE EMPRESA_OPTUS;
GO

USE EMPRESA_OPTUS;
GO

CREATE TABLE TIPO_DE_PERMISSAO (
idTipoDePermissao TINYINT PRIMARY KEY IDENTITY (1,1),
nomeTipoDePermissao VARCHAR(13) NOT NULL
);
GO

CREATE TABLE USUARIO (
idUsuario SMALLINT PRIMARY KEY IDENTITY (1,1),
idTipoDePermissao TINYINT FOREIGN KEY REFERENCES TIPO_DE_PERMISSAO(idTipoDePermissao),
nomeUsuario VARCHAR(30) NOT NULL,
emailUsuario VARCHAR(256) NOT NULL,
senhaUsuario VARCHAR(30) NOT NULL
);
GO

CREATE TABLE OPTUS (
idOptus TINYINT PRIMARY KEY IDENTITY (1,1),
idUsuario SMALLINT FOREIGN KEY REFERENCES USUARIO(idUsuario),
nomeEmpresa CHAR(5) NOT NULL
);
GO

CREATE TABLE GERENCIAMENTO (
idGerenciamento INT PRIMARY KEY IDENTITY (1,1),
idOptus TINYINT FOREIGN KEY REFERENCES OPTUS(idOptus)
);
GO

CREATE TABLE ESTILO (
idEstilo SMALLINT PRIMARY KEY IDENTITY(1,1),
nomeEstilo VARCHAR(30) NOT NULL
);
GO

CREATE TABLE CDS (
idCDs BIGINT PRIMARY KEY IDENTITY (1,1),
idEstilo SMALLINT FOREIGN KEY REFERENCES ESTILO(idEstilo),
nomeCD VARCHAR(30) NOT NULL
);
GO

CREATE TABLE ALBUM (
idAlbum INT PRIMARY KEY IDENTITY (1,1),
idGerenciamento INT FOREIGN KEY REFERENCES GERENCIAMENTO(idGerenciamento),
idCDs BIGINT FOREIGN KEY REFERENCES CDS(idCDs),
nomeAlbum VARCHAR(30) NOT NULL
);
GO