CREATE DATABASE LOCADORA_DE_VEICULOS;
GO

USE LOCADORA_DE_VEICULOS;
GO

CREATE TABLE EMPRESA (
idEmpresa TINYINT PRIMARY KEY IDENTITY(1,1),
nomeEmpresa VARCHAR(25) NOT NULL 
);
GO

CREATE TABLE MARCA (
idMarca TINYINT PRIMARY KEY IDENTITY(1,1),
nomeMarca VARCHAR(25) NOT NULL
);
GO

CREATE TABLE CLIENTES (
idClientes INT PRIMARY KEY IDENTITY(1,1),
nomeClientes VARCHAR(30) NOT NULL,
cpfClientes CHAR(11) NOT NULL UNIQUE 
);
GO

CREATE TABLE MODELO (
idModelo SMALLINT PRIMARY KEY IDENTITY(1,1),
idMarca TINYINT FOREIGN KEY REFERENCES MARCA(idMarca),
nomeModelo VARCHAR(30) NOT NULL
);
GO

CREATE TABLE VEICULO (
idVeiculo SMALLINT PRIMARY KEY IDENTITY(1,1),
idEmpresa TINYINT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
idModelo SMALLINT FOREIGN KEY REFERENCES MODELO(idModelo),
placa CHAR(7) NOT NULL UNIQUE
);
GO

CREATE TABLE ALUGUEIS (
idAluguel INT PRIMARY KEY IDENTITY(1,1),
idVeiculo SMALLINT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
idClientes INT FOREIGN KEY REFERENCES CLIENTES(idClientes),
inicioAluguel SMALLDATETIME NOT NULL,
fimAluguel SMALLDATETIME NOT NULL
);
GO