CREATE DATABASE CLINICA;
GO

USE CLINICA;
GO

CREATE TABLE CLINICA(
idClinica TINYINT PRIMARY KEY IDENTITY(1,1),
nomeClinica VARCHAR(25) NOT NULL,
endereco VARCHAR(25) NOT NULL
);
GO

CREATE TABLE VETERINARIO(
idVeterinario SMALLINT PRIMARY KEY IDENTITY(1,1),
idClinica TINYINT FOREIGN KEY REFERENCES CLINICA(idClinica),
nomeVeterinario VARCHAR(30) NOT NULL
);
GO

CREATE TABLE DONO(
idDono TINYINT PRIMARY KEY IDENTITY(1,1),
nomeDono VARCHAR(30) NOT NULL
);
GO

CREATE TABLE TIPOPET(
idTipoPet TINYINT PRIMARY KEY IDENTITY(1,1),
nomeTipoPet VARCHAR(30) NOT NULL
);
GO

CREATE TABLE RACA(
idRaca SMALLINT PRIMARY KEY IDENTITY(1,1),
idTipoPet TINYINT FOREIGN KEY REFERENCES TIPOPET(idTipoPet),
nomeRaca VARCHAR(30) NOT NULL 
);
GO

CREATE TABLE PETS(
idPets SMALLINT PRIMARY KEY IDENTITY(1,1),
idRaca SMALLINT FOREIGN KEY REFERENCES RACA(idRaca),
idDono TINYINT FOREIGN KEY REFERENCES DONO(idDono),
nomePet VARCHAR(30) NOT NULL
);
GO

CREATE TABLE ATENDIMENTO(
idAtendimento INT PRIMARY KEY IDENTITY(1,1),
idVeterinario SMALLINT FOREIGN KEY REFERENCES VETERINARIO(idVeterinario),
idPets SMALLINT FOREIGN KEY REFERENCES PETS(idPets),
dataAtendimento SMALLDATETIME NOT NULL,
tipoAtendimento VARCHAR(30) NOT NULL
);
GO